/*
 *  This file is part of easyFPGA.
 *  Copyright 2013,2014 os-cillation GmbH
 *
 *  easyFPGA is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  easyFPGA is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with easyFPGA.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package easyfpga.communicator;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.Arrays;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;
import java.util.logging.Level;
import java.util.logging.Logger;

import jssc.SerialPort;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import jssc.SerialPortTimeoutException;
import easyfpga.ConfigurationFile;
import easyfpga.exceptions.CommunicationException;

/**
 * The Communicator's backend that manages the communication with the virtual com port (ttyUSB)
 * using the Java Simple Serial Connector (jSSC) library. This class implements the
 * SerialPortListener that consumes events generated by the jSSC library.
 */
public class VirtualComPort implements SerialPortEventListener {

    private SerialPort port;
    private String deviceName;
    private final int baudrate = 3000000;
    private int serialNumber;
    private boolean searchBySerialNumber;

    private volatile LinkedBlockingQueue<Byte> receiveBuffer;
    private Communicator com;
    private ConfigurationFile configFile;

    private static final Logger LOGGER = Logger.getLogger(VirtualComPort.class.getName());

    /**
     * Default constructor
     */
    public VirtualComPort() {
        this.receiveBuffer = new LinkedBlockingQueue<Byte>();
        this.configFile = new ConfigurationFile();
        this.deviceName = configFile.getValue(ConfigurationFile.USB_DEVICE_KEY);
        this.searchBySerialNumber = false;
    }

    /**
     * Construct VirtualComPort. Search for the board with the given serial number
     *
     * @param serial number to be looked for
     */
    public VirtualComPort(int serial) {
        this();
        this.deviceName = null;
        this.serialNumber = serial;
        this.searchBySerialNumber = true;
    }

    /**
     * Set the communicator reference which is required for calling the Communicator's
     * processInterruptEvent method.
     *
     * @param com reference to the associated Communicator
     */
    public void setCommunicator(Communicator com) {
        this.com = com;
    }

    /**
     * Open the port and set up the listener. If no serial port device name is set the device
     * will be searched.
     *
     * @throws SerialPortException
     * @throws CommunicationException in case a serial is given but not found
     */
    public void open() throws SerialPortException, CommunicationException {
        LOGGER.entering(getClass().getName(), "open");
        /* find serial port if necessary */
        if (deviceName == null) {
            try {
                deviceName = getVCPDevice();
            }
            catch (IOException e) {
                SerialPortException ex;
                ex = new SerialPortException(deviceName, "VirtualComPort.open()",
                        SerialPortException.TYPE_PORT_NOT_FOUND);
                LOGGER.log(Level.SEVERE, "Throwing exception", ex);
                throw ex;
            }
        }

        /* init and open the port */
        setupPort();
    }

    /**
     * Open port and add receive listener
     *
     * @throws SerialPortException
     */
    private void setupPort() throws SerialPortException {

        /* open and init port */
        port = new SerialPort(deviceName);
        port.openPort();
        port.setParams(baudrate, 8, 1, 0);
        port.setFlowControlMode(SerialPort.FLOWCONTROL_RTSCTS_IN | SerialPort.FLOWCONTROL_RTSCTS_OUT);

        /* add listener for reception */
        int eventsMask = SerialPort.MASK_RXCHAR;
        port.setEventsMask(eventsMask);
        port.addEventListener(this);
    }

    /**
     * Close the port after purging buffers
     */
    public void close() {
        LOGGER.entering(getClass().getName(), "close");
        try {
            /* empty buffers (appears to fail on FT2232H) */
            port.purgePort(SerialPort.PURGE_TXABORT);
            port.purgePort(SerialPort.PURGE_RXABORT);

            /* close port */
            port.closePort();
        }
        catch (SerialPortException e) {
            e.printStackTrace();
        }
    }

    /**
     * Check whether the port is opened
     *
     * @return true if port is opened
     */
    public boolean isOpened() {
        return port.isOpened();
    }

    /**
     * Send an array of bytes to the VCP
     *
     * @param byteStream array of bytes to send
     */
    public void send(byte[] byteStream) {
        try {
            /* send byte stream */
            port.writeBytes(byteStream);
        } catch (SerialPortException e) {
            e.printStackTrace();
        }
    }

    /**
     * Send a frame instance over the VCP
     *
     * @param frame to send
     */
    public void send(Frame frame) {
        /* unbox Frame to byte[] */
        Byte[] byteObj = frame.getRawBytes();
        byte[] bytePrim = new byte[byteObj.length];

        for (int i = 0; i < byteObj.length; i++) {
            bytePrim[i] = byteObj[i];
        }

        /* send */
        try {
            port.writeBytes(bytePrim);
        }
        catch (SerialPortException e) {
            e.printStackTrace();
        }
    }

    /**
     * Block until a certain number of bytes is received. Remove the bytes from the receive buffer
     * before returning.
     *
     * @param byteCount Number of bytes to be received
     * @return Array of received bytes
     */
    public byte[] receive(int byteCount) {

        /* retrieve bytes from receiveBuffer (block until available) */
        byte[] received = new byte[byteCount];
        for (int i = 0; i < byteCount; i++) {
            try {
                received[i] = receiveBuffer.take();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }

        /* notify communicator (if present) */
        if (com != null) {
            com.receiveBufferChanged();
        }

        return received;
    }

    /**
     * Block until a certain number of bytes is received or a given timeout elapsed. Remove the
     * bytes from the receive buffer before returning.
     *
     * @param byteCount Number of bytes to be received
     * @param timeoutMillis timeout duration in milliseconds
     * @return Array of received bytes
     * @throws TimeoutException
     */
    public byte[] receive(int byteCount, long timeoutMillis) throws TimeoutException {

        /* prepare executor service, callable and future */
        ExecutorService executor = Executors.newSingleThreadExecutor();

        class ReceiveCallable implements Callable<byte[]> {
            int byteCount;
            public ReceiveCallable(int byteCount) {
                this.byteCount = byteCount;
            }

            @Override
            public byte[] call() throws Exception {
                return receive(byteCount);
            }
        };

        ReceiveCallable receiveCallable = new ReceiveCallable(byteCount);
        Future<byte[]> future = executor.submit(receiveCallable);

        /* receive */
        try {
            return (byte[]) future.get(timeoutMillis, TimeUnit.MILLISECONDS);
        }
        catch (InterruptedException e) {
            e.printStackTrace();
        }
        catch (ExecutionException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * Purge receive buffers
     */
    public void purge() {
        LOGGER.entering(getClass().getName(), "purge");

        /* remove listener and receive bytes in buffers */
        try {
            if (!port.removeEventListener()) {
                LOGGER.warning("Failed to remove jSSC serial event listener");
            }

            while (true) {
                byte[] byteLeft = port.readBytes(1, 100);
                LOGGER.fine(String.format("Purged byte: 0x%02X", byteLeft[0]));
            }
        }
        catch (SerialPortTimeoutException e) {
        }
        catch (SerialPortException e) {
            LOGGER.log(Level.SEVERE, "Throwing exception", e);
        }
        finally {
            /* clear local receive buffer */
            receiveBuffer.clear();
        }

        /* close and open port */
        close();
        try {
            open();
        }
        catch (SerialPortException e) {
            e.printStackTrace();
        }
        catch (CommunicationException e) {
            e.printStackTrace();
        }
    }

    /**
     * Invoked by jSSC library on incoming data. Reads and enqueues all data given by getEventValue,
     * then notify the communicator about the change in the receive buffer.
     */
    public void serialEvent(SerialPortEvent event) {
        if (event.isRXCHAR()) {

            try {
                /* read number of bytes given by event */
                for (int i = 0; i < event.getEventValue(); i++) {
                    /* read and enqueue */
                    receiveBuffer.put(port.readBytes(1)[0]);
                }

                /* notify communicator (if present) */
                if (com != null) {

                    /* call receiveBufferChanged notification method in a new thread */
                    Thread thr = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            com.receiveBufferChanged();
                        }
                    });
                    thr.start();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        /* !event.isRXCHAR() */
        else {
            LOGGER.warning("Unknown serial event");
        }

    }

    /**
     * Give a string representation of the receive buffer
     */
    public String getReceiveBufferString() {
        String outString = new String();
        int bufferSize = receiveBuffer.size();

        /* convert receiveBuffer to Byte[] */
        Byte[] byteBuffer = new Byte[bufferSize];
        byteBuffer = receiveBuffer.toArray(new Byte[bufferSize]);

        outString = "[";

        /* iterate over byteBuffer */
        for (int i=0; i < bufferSize; i++) {

            /* append data in hex, if data is null append ## */
            if (byteBuffer[i] != null) {
                outString += String.format("%02X", byteBuffer[i].byteValue());
            } else {
                outString += "##";
            }

            /* separate bytes using spaces */
            if (i < (bufferSize - 1)) {
                outString += " ";
            }
        }

        outString += "]";

        return outString;
    }

    /**
     * Get a reference to the receive buffer
     *
     * @return receive buffer
     */
    public LinkedBlockingQueue<Byte> getReceiveBuffer() {
        return receiveBuffer;
    }

    /**
     * Search in /dev/ for a ttyUSB device if it is not already set. Test all available
     * devices if a serial number is given.
     *
     * @return string containing the device path
     * @throws IOException
     * @throws SerialPortException
     * @throws CommunicationException when the boards with a given serial number is not found
     */
    private String getVCPDevice() throws IOException, SerialPortException, CommunicationException {
        LOGGER.entering(getClass().getName(), "getVCPDevice");

        /* get array of all device files containing ttyUSB*/
        File devFolder = new File("/dev");
        File[] files = devFolder.listFiles(new FilenameFilter() {

            @Override
            public boolean accept(File dir, String name) {
                return name.contains("ttyUSB");
            }
        });
        if (files == null || files.length == 0) {
            throw new FileNotFoundException();
        }

        if (!searchBySerialNumber) {
            /* return ttyUSBx if available (for debugging with interseptty) ... */
            for (File file : files) {
                if (file.getName().equals("ttyUSBx")) {
                    LOGGER.fine("Found ttyUSBx");
                    return file.getCanonicalPath();
                }
            }

            /* test whether port can be opened */
            Arrays.sort(files);
            for (File device : files) {
                boolean success = false;
                this.deviceName = device.getCanonicalPath();
                LOGGER.fine("Testing device " + this.deviceName);
                try {
                    setupPort();
                    if (isOpened()) success = true;
                }
                catch (SerialPortException ex) {
                    continue;
                }
                finally {
                    if (success) close();
                }
                if (success) {
                    LOGGER.info("Will return device: " + device.getCanonicalPath());
                    /* return device path string of the lowest port number than can be opened */
                    return device.getCanonicalPath();
                }
            }
            throw new CommunicationException("No easyFPGA board found.");
        }
        /* if serial number is given */
        else {
            return searchBoardWithSerialNumber(files);
        }
    }



    /**
     * Search the given device files for a device with matching serial number
     *
     * @param deviceFiles to be examined
     * @return string containing the device path of the matching device
     * @throws IOException
     * @throws SerialPortException
     * @throws CommunicationException in case no devices matches
     */
    private String searchBoardWithSerialNumber(File[] deviceFiles) throws
        IOException, SerialPortException, CommunicationException {
        LOGGER.entering(getClass().getName(), "searchBoardWithSerialNumber");

        int numberOfCheckedDevices = 0;

        /* test all devices for serial number */
        for (File deviceFile : deviceFiles) {

            /* setup vcp and com */
            this.deviceName = deviceFile.getCanonicalPath();
            setupPort();
            final Communicator com = new Communicator(this);

            LOGGER.info("Will now check device: " + this.deviceName);

            /* prepare ExecutorService that reads serial */
            ExecutorService executor = Executors.newSingleThreadExecutor();
            Callable<Integer> task = new Callable<Integer>() {
                public Integer call() {
                    return com.readSerial();
                }
            };
            Future<Integer> future = executor.submit(task);

            numberOfCheckedDevices++;

            /* compare the result */
            try {
                Integer serialRead = future.get(3000, TimeUnit.MILLISECONDS);
                if (serialRead.equals(this.serialNumber)) {
                    LOGGER.info("Found matching device: " + this.deviceName);
                    return this.deviceName;
                }
            }
            catch (TimeoutException toEx) {}
            catch (InterruptedException inEx) {}
            catch (ExecutionException exEx) {}
            finally {
                this.close();
            }

        }
        CommunicationException ex = new CommunicationException(String.format(
                "No device with serial number 0x%04X found. %d devices checked",
                serialNumber, numberOfCheckedDevices));
        LOGGER.log(Level.SEVERE, "Throwing exception", ex);
        throw ex;
    }
}
